apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: yahyabichiou/devops-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8089

        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/springdb

        - name: SPRING_DATASOURCE_USERNAME
          value: root

        - name: SPRING_DATASOURCE_PASSWORD
          value: root

        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update

        - name: SPRING_JPA_DATABASE_PLATFORM
          value: org.hibernate.dialect.MySQL8Dialect

---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
  - port: 8089
    targetPort: 8089
    nodePort: 30080
